import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'

import Header from '~/components/Header'
import Footer from '~/components/Footer'

import StyledComponentsRegistry from './styled-registry'
import { Providers } from './providers'

const nunito = Nunito({ subsets: ['latin'], weight: ['700', '400'] })

export const metadata: Metadata = {
  title: {
    default: "Home | Desafio Lacrei",
    template: "%s | Desafio Lacrei"
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={nunito.className}>
        <StyledComponentsRegistry>
          <Providers>
            <Header />
            {children}
            <Footer />
          </Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
